# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install datasets transformers torch

from datasets import load_dataset

print("Loading dataset...")

dataset = load_dataset("glue", "sst2")

print("Loaded successfully!")

# عرض sample
sample = dataset["train"][0]

print("\nSentence:", sample["sentence"])
print("Label:", sample["label"])

if sample["label"] == 1:
    print("Sentiment: Positive")
else:
    print("Sentiment: Negative")

